In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [3]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI


In [4]:
df.shape

(898, 35)

In [5]:
X = df.drop("Class" , axis =1)
y = df["Class"]

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [7]:
X

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,255403,1925.3650,691.8453,477.1796,0.7241,570.2536,0.9785,261028,0.7269,1.4499,...,-0.1398,2.2423,2.3704,2.7202,-25296416768,-19168882688,-18473392128,49.0869,43.0422,42.4153
894,365924,2664.8230,855.4633,551.5447,0.7644,682.5752,0.9466,386566,0.6695,1.5510,...,0.5611,3.4109,3.5805,3.9910,-31605219328,-21945366528,-19277905920,46.8086,39.1046,36.5502
895,254330,1926.7360,747.4943,435.6219,0.8126,569.0545,0.9925,256255,0.7240,1.7159,...,0.2665,2.2759,2.5090,2.6951,-22242772992,-19594921984,-17592152064,44.1325,40.7986,40.9769
896,238955,1906.2679,716.6485,441.8297,0.7873,551.5859,0.9604,248795,0.6954,1.6220,...,0.5325,2.6769,2.6874,2.7991,-26048595968,-21299822592,-19809978368,51.2267,45.7162,45.6260


In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [9]:
# split

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(

    X , y , test_size =0.2 , random_state = 42
)

In [10]:
X_train

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,0.3835,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687
740,343379,2360.4670,919.1130,479.2314,0.8533,661.2138,0.9657,355591,0.6926,1.9179,...,0.8084,13.2536,10.8915,5.0327,-6173152768,-10177111040,-13946608640,20.5354,27.7553,33.2095
231,80044,1059.0460,378.1419,270.6614,0.6983,319.2416,0.9883,80990,0.7521,1.3971,...,-0.1599,2.2247,2.4509,2.2165,-9834114048,-9082079232,-8377428480,54.3915,53.0591,50.5000
388,394009,2279.7581,770.8477,654.0494,0.5292,708.2852,0.9945,396190,0.7632,1.1786,...,1.6654,5.7796,9.1424,7.8056,-18411845632,-23242752000,-23591233536,34.5177,38.9835,38.4695
118,242874,1843.9160,647.9982,479.8817,0.6720,556.0906,0.9906,245181,0.7818,1.3503,...,-0.3694,2.4534,2.2759,2.5079,-46650236928,-40748339200,-32199612416,66.5225,62.6833,56.9092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,169573,1548.9830,594.8965,364.4516,0.7904,464.6580,0.9932,170738,0.8245,1.6323,...,-0.6257,2.4879,2.1186,2.4125,-35847098368,-33293408256,-27052677120,69.5829,67.4267,61.7498
270,102142,1223.5020,441.7251,296.5040,0.7412,360.6262,0.9863,103559,0.7847,1.4898,...,-0.5385,3.7325,3.9749,3.0696,-20307597312,-20240594944,-18247018496,68.7153,69.4312,65.9034
860,212397,1773.1410,649.3710,418.6798,0.7644,520.0310,0.9773,217331,0.7605,1.5510,...,0.1680,2.8597,2.8887,3.0498,-21660262400,-16450807808,-15513940992,50.1400,43.9826,43.0455
435,441826,2486.4771,942.0581,603.1290,0.7682,750.0336,0.9948,444138,0.8075,1.5620,...,1.7484,7.9695,9.3755,7.3022,-36332118016,-32863416320,-37779701760,43.0456,41.0627,43.2121


In [11]:
y_train

array([6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 4, 5, 2, 1, 2, 4, 4, 4, 5, 4, 6, 6,
       4, 2, 5, 5, 5, 4, 4, 2, 4, 6, 5, 6, 2, 0, 5, 1, 4, 3, 1, 2, 6, 2,
       2, 3, 2, 5, 2, 4, 0, 2, 6, 4, 2, 1, 4, 6, 5, 5, 5, 5, 3, 4, 3, 4,
       3, 6, 5, 2, 4, 1, 1, 3, 0, 3, 3, 4, 6, 2, 1, 4, 4, 5, 4, 5, 6, 2,
       3, 5, 2, 2, 4, 6, 2, 6, 1, 6, 2, 5, 5, 1, 1, 3, 6, 1, 2, 0, 4, 2,
       2, 4, 4, 3, 1, 2, 0, 4, 4, 1, 5, 3, 5, 1, 2, 2, 5, 3, 1, 4, 4, 2,
       0, 4, 1, 3, 0, 2, 4, 6, 0, 2, 3, 3, 0, 3, 6, 5, 2, 4, 5, 3, 5, 0,
       5, 4, 1, 0, 2, 2, 2, 5, 0, 2, 4, 4, 2, 4, 5, 5, 3, 4, 4, 2, 4, 5,
       2, 2, 4, 5, 1, 1, 4, 5, 1, 1, 4, 1, 4, 1, 2, 6, 6, 6, 4, 5, 1, 0,
       3, 0, 0, 2, 2, 5, 4, 5, 4, 2, 4, 5, 4, 2, 5, 5, 5, 3, 2, 4, 2, 5,
       0, 0, 3, 2, 4, 6, 5, 3, 2, 6, 6, 5, 2, 4, 0, 2, 0, 2, 2, 4, 5, 6,
       4, 2, 6, 4, 2, 2, 1, 4, 4, 6, 2, 2, 5, 3, 4, 1, 1, 5, 4, 2, 1, 6,
       2, 2, 5, 4, 2, 1, 5, 1, 1, 5, 2, 2, 0, 6, 4, 5, 3, 4, 1, 2, 5, 1,
       2, 5, 5, 4, 4, 2, 2, 5, 1, 5, 6, 6, 5, 3, 2,

In [12]:
X_test

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
331,143957,1452.2620,523.1368,352.3305,0.7392,428.1259,0.9844,146236,0.7746,1.4848,...,-0.3565,4.1478,3.4278,2.4134,-36987568128,-34249711616,-23752157184,77.3446,75.2287,62.9057
638,260563,1975.3740,762.5055,437.8510,0.8187,575.9854,0.9871,263977,0.6648,1.7415,...,0.3581,7.7778,16.2644,3.6606,-2424508160,-4791147520,-8197618688,16.2304,22.3860,28.8860
326,154245,1503.5980,546.4366,361.8018,0.7494,443.1601,0.9883,156070,0.7420,1.5103,...,0.3657,2.4202,2.9624,3.0045,-14960579584,-14010061824,-14057613312,48.2049,46.8561,46.4054
848,317794,2280.9690,875.5868,525.3380,0.8000,636.1037,0.9016,352462,0.6484,1.6667,...,0.3719,2.2682,2.1522,2.9676,-47417053184,-39451316224,-33127270400,58.7696,54.0476,50.8977
39,402279,2295.8630,798.9365,643.2753,0.5931,715.6797,0.9936,404887,0.7867,1.2420,...,1.9477,5.5889,12.5304,9.9496,-30746945536,-32178810880,-35126345728,43.7705,45.6162,46.3010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,283770,2096.7639,775.8751,468.8516,0.7968,601.0883,0.9737,291436,0.6751,1.6548,...,0.8440,11.0456,12.1213,6.1299,-4560918528,-7281993216,-9060293632,20.5245,25.8721,29.4805
25,381508,2239.7891,734.2203,666.2502,0.4202,696.9584,0.9919,384642,0.7398,1.1020,...,2.0740,6.6729,10.5392,9.3474,-25635362816,-25228310528,-28113027072,41.0071,41.1774,41.5364
84,253276,1961.0400,740.2677,437.3487,0.8068,567.8741,0.9822,257864,0.7493,1.6926,...,-0.1425,2.0920,1.9879,2.1549,-45574098944,-41109114880,-35898662912,64.4454,61.4443,58.3921
10,364495,2216.4900,790.9014,590.7698,0.6649,681.2411,0.9949,366374,0.7658,1.3388,...,0.9283,3.0514,4.3653,6.0898,-41679380480,-40727969792,-37574615040,52.7269,52.9888,50.3108


In [13]:
y_test

array([2, 5, 2, 6, 0, 2, 3, 2, 2, 1, 1, 2, 2, 2, 4, 4, 6, 5, 6, 1, 5, 4,
       2, 4, 5, 2, 0, 6, 0, 5, 6, 1, 2, 4, 2, 5, 0, 2, 2, 5, 1, 4, 5, 5,
       2, 1, 1, 2, 2, 5, 4, 3, 2, 6, 2, 4, 1, 2, 2, 0, 3, 6, 2, 2, 2, 6,
       1, 2, 4, 4, 2, 2, 4, 6, 3, 4, 2, 4, 5, 4, 2, 1, 4, 4, 2, 4, 2, 5,
       3, 2, 2, 5, 5, 3, 1, 2, 2, 2, 2, 4, 4, 3, 2, 5, 5, 4, 3, 4, 4, 2,
       5, 2, 4, 4, 4, 6, 1, 5, 5, 4, 4, 2, 5, 1, 5, 5, 6, 1, 4, 4, 2, 1,
       3, 4, 4, 2, 4, 2, 5, 0, 5, 5, 5, 6, 6, 5, 2, 0, 0, 5, 6, 4, 6, 1,
       1, 5, 6, 1, 2, 3, 5, 2, 6, 5, 0, 0, 2, 4, 2, 4, 1, 6, 5, 6, 6, 5,
       0, 1, 0, 2])

In [14]:
# Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() # instance create of class StandardScaler

X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)


In [15]:
X_train_scale

array([[ 0.58688241,  0.77313761,  0.65494348, ...,  0.30093727,
        -0.16212317, -0.02461782],
       [ 0.3914469 ,  0.71185715,  1.13717993, ..., -1.80898088,
        -1.46032963, -1.34892074],
       [-2.06406201, -2.47260549, -2.61727944, ...,  0.29158724,
         0.32348907,  0.24572657],
       ...,
       [-0.8299155 , -0.72527788, -0.73488935, ...,  0.02780714,
        -0.3163686 , -0.44177804],
       [ 1.30943154,  1.02019277,  1.29642401, ..., -0.41235787,
        -0.5222101 , -0.42641305],
       [-0.82667985, -0.85456781, -0.88171807, ...,  0.35510789,
         0.44927523,  0.44102602]], shape=(718, 34))

In [16]:
X_test_scale

array([[-1.46809512, -1.51044055, -1.61098268, ...,  1.71568954,
         1.88635897,  1.38986445],
       [-0.38078401, -0.23043153,  0.05028916, ..., -2.07608033,
        -1.83884423, -1.74766326],
       [-1.37216304, -1.38482587, -1.44927691, ..., -0.09225422,
        -0.11379811, -0.13190525],
       ...,
       [-0.44873279, -0.26550556, -0.1040461 , ...,  0.91537148,
         0.9146128 ,  0.97358961],
       [ 0.58834638,  0.3595581 ,  0.247363  , ...,  0.18830878,
         0.3185332 ,  0.22827726],
       [-1.35551852, -1.22973814, -1.10752165, ...,  1.30474726,
         1.61369423,  1.4415299 ]], shape=(180, 34))

In [17]:
y_train.shape

(718,)

### Deep Learning

In [18]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

In [19]:
import torch  # short Pytorch - torch

print(torch.__version__)
print(torch.cuda.is_available())

2.13.0+cu126
True


In [20]:
# Convert data into Tensors

import torch.nn as nn

X_train_tensor = torch.tensor(X_train_scale , dtype = torch.float32)
X_test_tensor = torch.tensor(X_test_scale , dtype = torch.float32)
y_train_tensor = torch.tensor(y_train , dtype = torch.long )
y_test_tensor = torch.tensor(y_test , dtype = torch.long)

In [21]:
# Loss fnx for classification problem Cross entropy , target value expect long format that's why - torch.long

In [22]:
type(y_train)

numpy.ndarray

In [23]:
# Tensor Data set - To define Dataset, access from Memory(RAM)

In [24]:
from torch.utils.data import TensorDataset , DataLoader

#train_dataset = TensorDataset(in_features , op_features)
#instance create for class TensorDataset

train_dataset = TensorDataset(X_train_tensor , y_train_tensor)
test_dataset = TensorDataset(X_test_tensor , y_test_tensor)


In [25]:
# Data Loader - To define how the data will be loaded for traning

In [26]:
train_loader = DataLoader(train_dataset , batch_size =32 , shuffle = True)
test_loader = DataLoader(test_dataset , batch_size = 32)

In [27]:
X_train.shape[1]

34

### Build Model

In [28]:
class ANN(nn.Module):
    def __init__(self):
        super(ANN , self).__init__()

        self.model = nn.Sequential(

            # 1st hidden layer
            # nn.AF(in_feature , op_feature),

            nn.Linear(X_train.shape[1] , 64),
            nn.ReLU(),

            # 2nd hidden layer

            nn.Linear(64,64),
            nn.ReLU(),

            #O/P Layer

            nn.Linear(64,7)
            # Softmax() - by deafult cross entropy - Cost fnx - there apply
            
            
        )

    def forward(self , x):
        return self.model(x)

        

In [29]:
import torch.optim as optim

model = ANN()

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())




### Train Model

In [34]:
epochs = 100

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for xb , yb in train_loader:

        optimizer.zero_grad() # for each batch fresh gradient compute, dont accumualte value of graident of previous batch
        
        output = model(xb)  #forward propgation... predicted value for this batch
        loss = criterion(output, yb)  # Loss compute
        loss.backward() # Gradient compute automatically
        optimizer.step() # learn params update

        running_loss += loss  # Total running loss cal for all batches(23) in 1 epoch

    train_loss = running_loss/len(train_loader)  # Avg loss per batch for 1 epoch
        
    print(f"epoch = {epoch}/{epochs} , loss = {train_loss}")    
        
        
        
    
    



epoch = 0/100 , loss = 0.004824623465538025
epoch = 1/100 , loss = 0.007874419912695885
epoch = 2/100 , loss = 0.0051274849101901054
epoch = 3/100 , loss = 0.0052550421096384525
epoch = 4/100 , loss = 0.004760566167533398
epoch = 5/100 , loss = 0.004686618223786354
epoch = 6/100 , loss = 0.004083449952304363
epoch = 7/100 , loss = 0.0033673751167953014
epoch = 8/100 , loss = 0.004196315538138151
epoch = 9/100 , loss = 0.008600560016930103
epoch = 10/100 , loss = 0.019333114847540855
epoch = 11/100 , loss = 0.008212568238377571
epoch = 12/100 , loss = 0.00909089669585228
epoch = 13/100 , loss = 0.003727551084011793
epoch = 14/100 , loss = 0.004381523933261633
epoch = 15/100 , loss = 0.0033755467738956213
epoch = 16/100 , loss = 0.0035085587296634912
epoch = 17/100 , loss = 0.004486429039388895
epoch = 18/100 , loss = 0.0026868435088545084
epoch = 19/100 , loss = 0.002921786392107606
epoch = 20/100 , loss = 0.003486697329208255
epoch = 21/100 , loss = 0.003282645484432578
epoch = 22/100 

In [33]:
len(train_loader)

23

In [35]:
print(model)

ANN(
  (model): Sequential(
    (0): Linear(in_features=34, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=7, bias=True)
  )
)


In [36]:
print(list(model.parameters()))  # best weight & bias value

[Parameter containing:
tensor([[-0.2152, -0.0190,  0.0477,  ...,  0.0489, -0.0467,  0.1497],
        [ 0.1041,  0.1069, -0.1202,  ...,  0.1828, -0.1161, -0.0995],
        [ 0.0186, -0.0555, -0.3049,  ...,  0.1564,  0.1581,  0.1179],
        ...,
        [ 0.2578,  0.1695,  0.1563,  ..., -0.1431, -0.1884, -0.3403],
        [ 0.3149, -0.0440,  0.3177,  ..., -0.6315,  0.0769, -0.1273],
        [-0.0047,  0.1082,  0.0584,  ..., -0.2223,  0.1124,  0.0474]],
       requires_grad=True), Parameter containing:
tensor([ 0.2218,  0.0065,  0.0873,  0.1314,  0.0651,  0.3590,  0.1528,  0.0635,
         0.1203, -0.0505, -0.0038,  0.1072,  0.3660,  0.2802, -0.0021,  0.1854,
         0.1702,  0.1260,  0.0354,  0.2483,  0.3212, -0.1885,  0.0185,  0.0162,
         0.0863,  0.0540,  0.3716,  0.0876,  0.0942,  0.1860,  0.3006, -0.1536,
         0.0746,  0.0559, -0.1128,  0.0019,  0.0009, -0.0069,  0.0742,  0.2501,
         0.3377, -0.0631,  0.3480, -0.0607,  0.3996, -0.0367,  0.0764,  0.2327,
        -0.01

### Evaluation

In [46]:
model.eval()

total = 0
correct = 0  # correct pred

with torch.no_grad():

    for xb , yb in test_loader:
        output = model(xb) #Forward Propgation , pred value
        _, pred = torch.max(output,1) # torch.max - return max value and index
        # here pred = index
        # o/p  - 7 values [1, 0.6, 1.4 , 0.5 , -0.2 , 1.2, 0.1 ]
        #( max value = 1.4 , index = 2)

        correct += (pred == yb).sum().item()  # sum store for all batches

        

    





In [47]:
print(correct)

167


In [48]:
print(correct/180 *100)

92.77777777777779


In [39]:
print(yb.shape)

torch.Size([20])


In [40]:
y_test.shape

(180,)